### PR TITLE
Team statistics refactor

### PR DESCRIPTION
**Pull request by ggerdsen**
added TeamStatistics class

### CODE REVIEW

**Review by Truthvendor — APPROVED** [review]
New file created so no merge conflicts possible.

**Comment by jKwibe** [comment]
Looks neat! 🎇

**Review by jKwibe — APPROVED** [review]
Looks neat! 🎇🔥

**Review by Strompy — APPROVED** [review]
Looks like this includes the fixes for previous errors for the stat_tracker

**Pull request merged**
